api_platform:
    title: Devscast API
    description: devs-cast.com, the idea behind it is to have a platform of podcasts in web devs and articles on web devs (javascript) and algorithm in general, the platform also provides quotes in the fields of software programming and algorithm challenge to improve your own level in programming
    version: 1.0.0
    show_webby: false
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
