security:
    encoders:
        App\Entity\User:
            algorithm: auto

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true

            form_login:
                check_path: login
                login_path: login
                csrf_token_generator: security.csrf.token_manager
                default_target_path: admin.index

            logout:
                path: logout
                target: home

    access_control:
         - { path: ^/admin, roles: ROLE_ADMIN }
