vich_uploader:
    db_driver: orm

    mappings:
        post_thumb:
            uri_prefix: /images/post
            upload_destination: '%kernel.project_dir%/public/images/post'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true

        blog_thumb:
            uri_prefix: /images/blog
            upload_destination: '%kernel.project_dir%/public/images/blog'
            namer: Vich\UploaderBundle\Naming\UniqidNamer

        category_icon:
            uri_prefix: /images/category
            upload_destination: '%kernel.project_dir%/public/images/category'
            namer: Vich\UploaderBundle\Naming\UniqidNamer

        user_avatar:
            uri_prefix: /images/avatars
            upload_destination: '%kernel.project_dir%/public/images/avatars'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
